import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { signUp } from 'next-auth-sanity/client';
import { signIn } from 'next-auth/react';

export default function Home() {
  const [Data, setData] = useState({
    name: "",
    email: "",
    password: ""
  });
  const handleSignUp = async (e) => {
    e.preventDefault();
    console.log(Data);
    try {
      
      const user = await signUp({
    email : Data.email,
    password : Data.password,
    name: Data.name,
      });
      console.log(user);
    } catch (error) {
      console.log(error);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form>
        <input onChange={(e) => setData({...Data, email: e.target.value })} placeholder='email' type='email' value={Data.email}></input>
        <input onChange={(e) => setData({...Data, password: e.target.value })} placeholder='name' type='text' value={Data.password}></input>
        <input onChange={(e) => setData({...Data, name: e.target.value })} placeholder='password' type='password' value={Data.name}></input>
        <button onClick={handleSignUp} type='submit'>Sign Up</button>
     </form>
      
    </div>
  )
}
